### ISSUE TITLE
Do not process test in normal case

### ISSUE THREAD

**Issue by sibskull** [test-unit/test-unit#124] opened 2016-09-13 15:55 UTC
I try to process pack of test/test_*.rb file using script with test-unit-3.2.1:
```
#!/usr/bin/ruby
require 'test/unit'
(r = Test::Unit::AutoRunner.new(true)).process_args(ARGV) or
  abort r.options.banner + " tests..."
exit r.run()
```

Just run for existing files:
```
[builder@localhost sqlite3-ruby-1.3.11]$ testrb -vp -Ilib:ext test/test_*.rb
[builder@localhost sqlite3-ruby-1.3.11]$ echo $?
1
```
But if I add missing file name, all tests are passed:
```
[builder@localhost sqlite3-ruby-1.3.11]$ testrb -vp -Ilib:ext test/test_*.rb zzz
O
Run options: --seed 28976

# Running:

.....................................................................................................................................................................................................................................

Finished in 0.087542s, 2615.8928 runs/s, 4237.9748 assertions/s.

229 runs, 371 assertions, 0 failures, 0 errors, 0 skips
[builder@localhost sqlite3-ruby-1.3.11]$ echo $?
0

```
Why I need error for real pass test?

**Comment by kou** [comment] 2016-09-14 01:36
You didn't use test-unit. You used test/unit that is a wrapper of minitest. The test/unit is bundled until Ruby 2.2. Please confirm your Ruby version.

**Comment by sibskull** [comment] 2016-09-14 03:23
Ruby 2.3.1

**Comment by sibskull** [comment] 2016-09-14 03:29
Well, there are two instance:
```
$ rpm -qf /usr/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit.rb
ruby-stdlibs-2.3.1-alt1
$ rpm -qf /usr/lib/ruby/site_ruby/test/unit.rb                          
ruby-test-unit-3.2.1-alt1
```
What version do you advice to use? And how to use separate test-unit (sorry, I'm newbie in Ruby)?

**Comment by kou** [comment] 2016-09-18 13:07
Could you provide (test) scripts that reproduce the problem? I want to try them on my environment.

**Comment by sibskull** [comment] 2016-09-20 11:43
In my first post:
```
#!/usr/bin/ruby
require 'test/unit'
(r = Test::Unit::AutoRunner.new(true)).process_args(ARGV) or
  abort r.options.banner + " tests..."
exit r.run()
```

**Comment by kou** [comment] 2016-09-20 11:56
It doesn't include any tests. I can't reproduce only with it.
If you can't provide any information, I'll close this issue.

**Comment by sibskull** [comment] 2016-09-21 10:11
Hmm, I try to test http://rubyforge.org/projects/sqlite-ruby/, but only on their internal tests test/unit fails.
Simple test works correct. I cannot reproduce beyong sqlite-ruby. :(

Please, close this issue.

**Comment by sibskull** [comment] 2016-09-21 10:23
Debug show
/usr/lib/ruby/site_ruby/test/unit/autorunner.rb:427:        return false if suite.nil?
for suite is nil and method is return false.

**Comment by sibskull** [comment] 2016-09-21 11:29
I found error. sqlite-ruby inherits testcases from Minitest::Test istead of Test::Unit and `/usr/lib/ruby/site_ruby/test/unit/collector/load.rb:69:          TestCase::DESCENDANTS`
returns TestCase::DESCENDANTS as [].

**Comment by kou** [comment] 2016-09-22 06:18
Thanks for looking into it.
test-unit doesn't care about tests written for minitest.

**Closed by kou** 2016-09-22 06:18 UTC
