### ISSUE TITLE
test-unit 3.1 crashes with rails 3.2

### ISSUE THREAD

**Issue by donpdonp** [test-unit/test-unit#119] opened 2016-03-14 17:41 UTC
While starting some maintenance for an older rails app (3.2) and the latest test-unit (3.1), this exception started to be thrown for rails console:
```
$ bin/rails c
set_default_options has been deprecated, use set_options
/home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:16:in `method': undefined method `start' for class `Module' (NameError)
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:16:in `<module:BacktraceFilter>'
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:9:in `<module:Util>'
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:8:in `<module:Unit>'
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:7:in `<module:Test>'
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/test-unit-3.1.7/lib/test/unit/util/backtracefilter.rb:6:in `<top (required)>'
	from /home/donp/code/cointhink/rails/gems/ruby/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
```

by setting test-unit to an older version
```diff
-gem 'test-unit'
+gem 'test-unit', '~>3.0.9'
```

the problem is fixed.
```
$ bundle
Using rails 3.2.22.1
Installing test-unit 3.0.9 (was 3.1.7)

$ bin/rails c
set_default_options has been deprecated, use set_options
Loading development environment (Rails 3.2.22.1)
[1] pry(main)> 
```

**Comment by kou** [comment] 2016-03-15 00:16
What version of power_assert gem are you using? Are you using the latest version?

**Comment by donpdonp** [comment] 2016-03-15 00:23
The Gemfile does not list power_assert, but something is including it because its in the Gemfile.lock. In both cases (crash, and working) power_assert is 0.2.7.

**Comment by kou** [comment] 2016-03-15 00:48
Thanks.
It seems that your `bin/rails c` doesn't require `power_assert` correctly. Your `PowerAssert` module may be empty module that is defined by Active Support automatically.

How about stop requiring test-unit for `bin/rails c`? Because test-unit isn't used for `bin/rails c`.

```ruby
gem 'test-unit, :require => false
```

**Comment by kou** [comment] 2016-03-16 02:11
Could you show your Gemfile and Gemfile.lock?

**Comment by donpdonp** [comment] 2016-03-16 02:17
Thanks for the help, but I'm happy with downgrading the gem and leaving it at that. I posted the issue because it looks like a test-unit regression. If thats not the case, then the issue can be closed.

**Comment by kou** [comment] 2016-03-16 07:32
I can't judge whether test-unit has a regression or not unless I can reproduce it... :<
Anyway, I close this issue. Thanks for your report.

**Closed by kou** 2016-03-16 07:32 UTC
